"use client";

import {
  personal,
  experience,
  skills,
  certifications,
  projects,
} from "@/lib/data";
import { Download, FileText } from "lucide-react";

export function ResumeApp() {
  return (
    <div className="w-full h-full overflow-y-auto bg-os-desktop">
      <div className="sticky top-0 z-10 flex items-center justify-between px-4 py-2 bg-os-panel/90 border-b border-os-border/50 backdrop-blur">
        <div className="flex items-center gap-2 text-xs font-mono text-os-text-muted">
          <FileText className="w-3.5 h-3.5 text-os-cyan" /> /resume.txt
        </div>
        <a
          href={personal.resumeUrl}
          download
          className="inline-flex items-center gap-1.5 text-xs px-2.5 py-1 rounded bg-os-cyan/15 hover:bg-os-cyan/25 text-os-cyan border border-os-cyan/40"
        >
          <Download className="w-3.5 h-3.5" /> Download PDF
        </a>
      </div>

      <div className="p-5 max-w-3xl mx-auto text-sm font-mono leading-relaxed">
        <pre className="text-os-cyan mb-2 text-xs">{`╔══════════════════════════════════════════════════════════════╗
║                  ${personal.name.padEnd(42)}║
║                  ${personal.headline.padEnd(42)}║
╚══════════════════════════════════════════════════════════════╝`}</pre>

        <div className="text-os-text-muted text-xs">
          {personal.location} · {personal.email} · {personal.phone}
        </div>

        <Section title="SUMMARY">
          {personal.bio.slice(0, 2).join(" ")}
        </Section>

        <Section title="EXPERIENCE">
          <ul className="space-y-3">
            {experience.map((e, i) => (
              <li key={i}>
                <div className="text-os-cyan">
                  {e.role} — {e.company}
                </div>
                <div className="text-os-text-muted text-xs">{e.period}</div>
                <div className="text-os-text/90 text-xs">{e.description}</div>
              </li>
            ))}
          </ul>
        </Section>

        <Section title="SELECTED PROJECTS">
          <ul className="space-y-1">
            {projects.slice(0, 5).map((p) => (
              <li key={p.id} className="text-xs">
                <span className="text-os-cyan">{p.title}</span>{" "}
                <span className="text-os-text-muted">— {p.tagline}</span>
              </li>
            ))}
          </ul>
        </Section>

        <Section title="SKILLS">
          <ul className="space-y-0.5 text-xs">
            {skills.map((s) => (
              <li key={s.category}>
                <span className="text-os-cyan">{s.category}:</span>{" "}
                <span className="text-os-text/90">{s.items.join(", ")}</span>
              </li>
            ))}
          </ul>
        </Section>

        <Section title="CERTIFICATIONS">
          <ul className="space-y-0.5 text-xs">
            {certifications.map((c) => (
              <li key={c}>• {c}</li>
            ))}
          </ul>
        </Section>

        <div className="mt-6 text-[10px] text-os-text-muted">
          Generated by LinfyOS v1.0 — for the live PDF, click Download above.
        </div>
      </div>
    </div>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="mt-5">
      <div className="text-os-green term-glow text-xs tracking-widest">
        ── {title} ──
      </div>
      <div className="mt-2 text-os-text">{children}</div>
    </div>
  );
}
